In [49]:
import numpy as np

***Write a Numpy program to get the Numpy version and show the Numpy build configuration.***

In [35]:
print(np.__version__)

1.24.3


In [36]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hp/anaconda3/anaconda1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
 

***Write a NumPy program to create an array with basic functions*** 

In [37]:
x = np.array([1,2,3,4,5,6])
print(x)

print(type(x))
print(len(x))
print(x.ndim)
print(x.shape)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
6
1
(6,)


***Write a NumPy program to test whether none of the elements of a given array are zero.***

In [38]:
x = np.array([1,2,3,4,5])
print(x) # print original array
print(np.all(x)) # True, since no zero is present

x = np.array([0,1,2,3,4])
print(x)
print(np.all(x)) # False, zero is present

[1 2 3 4 5]
True
[0 1 2 3 4]
False


***Write a NumPy program to test if any of the elements of a given array are non-zero.***

In [39]:
x = np.array([1,0,0,0])
print(x) # print original array
print(np.any(x)) # True, since one non-zero is present

x = np.array([0,0,0,0])
print(x)
print(np.any(x)) # False, no non-zero is present

[1 0 0 0]
True
[0 0 0 0]
False


***Write a NumPy program to test element-wise for complex numbers***

In [40]:
x = np.array([1+2j, 6, 98.76, 7j])
print(x)
print(np.iscomplex(x))
print(np.isreal(x))

[ 1.  +2.j  6.  +0.j 98.76+0.j  0.  +7.j]
[ True False False  True]
[False  True  True False]


***Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.***

In [41]:
x = np.array([6,5,8])
y = np.array([1,9,8])
print(x, y)

# np.greater(), np.greater_equal(), np.less,....
print(np.greater(x, y))
print(np.less_equal(x, y))

[6 5 8] [1 9 8]
[ True False False]
[False  True  True]


***Write a NumPy program to create an array and determine the size of the memory occupied by the array.***

In [42]:
x = np.array([6,1050,88])
print(x)
print("%d bytes" % (x.size*x.itemsize))

[   6 1050   88]
12 bytes


***Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.***

In [43]:
x = np.zeros(10)
print(x)

x = np.ones(10)
print(x)

x = np.ones(10) *5
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


***Write a NumPy program to create an array of even integers from 10 to 60.***

In [44]:
x =np.arange(10,61,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60]


***Write a NumPy program to create a 3x3 identity matrix.***

In [45]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***Write a NumPy program to generate three random number between 0 and 10.***

In [46]:
rand_n = np.random.normal(1,10,3)
print(rand_n)

[ 11.94704745  -5.50477697 -11.39128985]


***Write a NumPy program to create a 3X4 array and iterate over it.***

In [52]:
xy = np.arange(1,13).reshape((3,4))
print(xy)

for x in np.nditer(xy):
    print(x, end = '  ' )

print('\n')
print(xy.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1  2  3  4  5  6  7  8  9  10  11  12  

2


***Write a NumPy program to create a 1-d array of 18 elements.***

In [53]:
x = np.arange(18)
print(x)
print(x.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
1


***Write a NumPy program to create a vector of array and reshaping it.***

In [54]:
y = x.reshape(6,3,1)
print(y)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]

 [[15]
  [16]
  [17]]]


In [63]:
x = np.array([[1,3],
              [2,4]])
y = np.array([[2,7],
              [3,2]])


***Write a NumPy program to multiply two given arrays of the same size element-by-element.***

In [64]:
print(np.multiply(x, y))

[[ 2 21]
 [ 6  8]]


***Write a NumPy program to add two given arrays of the same size element-by-element.***

In [65]:
print(np.add(x, y))

[[ 3 10]
 [ 5  6]]


***Write a NumPy program to subtract two given arrays of the same size element-by-element.***

In [66]:
print(np.subtract(x, y))

[[-1 -4]
 [-1  2]]


***Write a NumPy program to dot product two given arrays of the same size element-by-element.***

In [67]:
print(x.dot(y))
print(np.dot(x, y))

[[11 13]
 [16 22]]
[[11 13]
 [16 22]]


***Write a NumPy program to dot product two given arrays of the same size element-by-element.***

In [68]:
print(np.divide(x, y))

[[0.5        0.42857143]
 [0.66666667 2.        ]]


***Write a NumPy program to return sum of all array element over a given axis.***

In [72]:
print(x)

[[1 3]
 [2 4]]


In [69]:
print(np.sum(x))

10


In [70]:
print(np.sum(x, axis = 0))

[3 7]


In [71]:
print(np.sum(x, axis = 1))

[4 6]


***Write a NumPy program to swap rows and columns of a given array in reverse order.***

In [74]:
x = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])

In [75]:
print(x[::-1,::-1])

[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


***Write a NumPy program to sort a given array by row and column in ascending order.***

In [82]:
a = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])


In [83]:
print(np.sort(a)) # row

[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]


In [85]:
print(np.sort(a, axis=0)) # col

[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]
